steps:
  # ==============================
  # 1) Build Docker image
  # ==============================
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "us-east1-docker.pkg.dev/$PROJECT_ID/taskmanager-repo/taskmanager-back-repo-qas:latest",
        "."
      ]

  # ==============================
  # 2) Push image to Artifact Registry
  # ==============================
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "us-east1-docker.pkg.dev/$PROJECT_ID/taskmanager-repo/taskmanager-back-repo-qas:latest"
      ]

  # ==============================
  # 3) Deploy to Cloud Run (QAS)
  # ==============================
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "taskmanager-back-qas",
        "--region=us-east1",
        "--platform=managed",
        "--image=us-east1-docker.pkg.dev/$PROJECT_ID/taskmanager-repo/taskmanager-back-repo-qas:latest",
        "--allow-unauthenticated",
        "--cpu=1",
        "--memory=1Gi",
        "--port=8080",
        "--set-env-vars", "DB_HOST=/cloudsql/$PROJECT_ID:us-east1:taskmanager-sql-db",
        "--set-env-vars", "DB_USER=taskmanageruser",
        "--set-env-vars", "DB_NAME=taskmanagerdb",
        "--set-secrets", "DB_PASS=taskmanager-backend-password:latest",
        "--add-cloudsql-instances=$PROJECT_ID:us-east1:taskmanager-sql-db",
        "--vpc-connector=vpc-connector-taskmanager",
        "--vpc-egress=all-traffic"
      ]

# ==============================
# Store build logs in Cloud Storage
# ==============================
options:
  logging: CLOUD_LOGGING_ONLY

# ==============================
# Artifact Registry retention policy
# ==============================
images:
  - "us-east1-docker.pkg.dev/$PROJECT_ID/taskmanager-repo/taskmanager-back-repo-qas:latest"
