# cloudbuild.yaml
# Ejecuta en Cloud Build. Usa los secretos definidos en el proyecto: _DB_USER_SECRET_NAME, _DB_PASSWORD_SECRET_NAME
steps:
  # 1) Build image (docker build)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/taskmanager-back-repo-qas/taskmanager-back-qas:$SHORT_SHA', '.']

  # 2) Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/taskmanager-back-repo-qas/taskmanager-back-qas:$SHORT_SHA']

  # 3) Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        IMAGE="us-east1-docker.pkg.dev/$PROJECT_ID/taskmanager-back-repo-qas/taskmanager-back-qas:$SHORT_SHA"
        echo "Deploying $$IMAGE to Cloud Run service taskmanager-back-qas..."

        gcloud run deploy taskmanager-back-qas \
          --image="$$IMAGE" \
          --region=us-east1 \
          --platform=managed \
          --service-account=sa-cloudrun-taskmanager@cv-taskmanagertienda-qas.iam.gserviceaccount.com \
          --cpu=1 \
          --memory=1Gi \
          --port=8080 \
          --allow-unauthenticated \
          --add-cloudsql-instances=$PROJECT_ID:us-east1:taskmanager-sql-db \
          --set-env-vars=DB_HOST=/cloudsql/$PROJECT_ID:us-east1:taskmanager-sql-db,DB_NAME=taskmanagerdb \
          --set-secrets=DB_USER=$_DB_USER_SECRET_NAME:latest \
          --set-secrets=DB_PASS=$_DB_PASSWORD_SECRET_NAME:latest \
          --vpc-connector=serverless-connector-qas \
          --vpc-egress=all-traffic

images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/taskmanager-back-repo-qas/taskmanager-back-qas:$SHORT_SHA'

substitutions:
  _DB_USER_SECRET_NAME: "_DB_USER_SECRET_NAME"
  _DB_PASSWORD_SECRET_NAME: "_DB_PASSWORD_SECRET_NAME"

options:
  logging: CLOUD_LOGGING_ONLY
